### PR TITLE
FMarketLowestPrice: better error handling, minor refactoring

### LINKED ISSUE #1448: [INFO NEEDED] Lowest Price Market on Sell Listing Bug
### Expected Behavior
My lowest price sell listing works well on page 2.
image

### Actual Behavior
But on page 1 it goes wrong. The listing date & my sell price is shifted to right, & the lowest sell price is gone. It just happens today
image
I've tried to clear cached data or even reinstalling Augmented Steam but the bug persists.

### Steps to Reproduce the Problem
  1. Well, just open your sell listing at Steamcommunity Market

### Specifications
  - Augmented Steam Version: 2.3.2
  - Browser Version: Chrome Version 103.0.5060.114 (Official Build) (64-bit)
All updated

### PR DESCRIPTION
**Pull request by candela97**
1. Better error handling to fix #1448, which is likely due to `Price.parseFromString()` throwing when `data.lowest_price` is `undefined`. Also indicate when price data is loading, when an error occurred, and when data is missing.
2. About TODO comments -- the width changes are indeed necessary to fix spacing due to the additional "game name" header inserted by the sorting feature. But it can probably be removed after #1481.
3. Changed some class names and minor refactoring for clarity. Also limited the number of retries after a timeout to 2. The original code didn't seem to have a limit...
4. Merged market-related CSS styles.
5. This and market sorting needs to be reapplied on page changes, so they should be rewritten as callback features. I'll try working on that later.

### CODE REVIEW

File: src/js/Content/Features/Community/MarketHome/FMarketLowestPrice.js [hunk 1]
```diff
@@ -75,61 +57,72 @@ export default class FMarketLowestPrice extends Feature {
             const linkNode = node.querySelector(".market_listing_item_name_link");
             if (!linkNode) { continue; }
 
-            const m = linkNode.pathname.match(/\/(\d+)\/(.+)$/);
-            if (!m) { continue; }
-            const marketHashName = m[2];
+            const [, appid, marketHashName] = linkNode.pathname.match(/^\/market\/listings\/(\d+)\/([^/]+)/) || [];
```
Comment (candela97) [inline src/js/Content/Features/Community/MarketHome/FMarketLowestPrice.js:60]: This is the same regexp used in CMarketListing.js to parse the link. Maybe it should be factored out to GameId.js?

File: src/js/Content/Features/Community/MarketHome/FMarketLowestPrice.js [hunk 2]
```diff
@@ -75,61 +57,72 @@ export default class FMarketLowestPrice extends Feature {
...
 
         do {
             try {
-                const data = await RequestData.getJson(
-                    `https://steamcommunity.com/market/priceoverview/?country=${User.storeCountry}`
-                    + `&currency=${CurrencyManager.currencyTypeToNumber(CurrencyManager.storeCurrency)}`
-                    + `&appid=${appid}`
-                    + `&market_hash_name=${marketHashName}`
+                data = await RequestData.getJson(
+                    `https://steamcommunity.com/market/priceoverview/?country=${country}&currency=${currencyNumber}&appid=${appid}&market_hash_name=${marketHashName}`
```
Comment (candela97) [inline src/js/Content/Features/Community/MarketHome/FMarketLowestPrice.js:100]: This endpoint is used in several features, and is probably worth factoring out the avoid importing `User` and `CurrencyManager` just to build this URL.
